"""empty message

Revision ID: 381e254f7905
Revises: e0d016c860b4
Create Date: 2025-06-23 14:48:41.595740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '381e254f7905'
down_revision = 'e0d016c860b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
