"""rename testing_1 to names

Revision ID: 60ab35a5e13c
Revises: 657c8563c894
Create Date: 2025-06-16 15:59:00.665751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60ab35a5e13c'
down_revision = '657c8563c894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('testing_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testing_1',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('names')
    # ### end Alembic commands ###
