"""rename testing_1 to names

Revision ID: 60ab35a5e13c
Revises: 657c8563c894
Create Date: 2025-06-16 15:59:00.665751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60ab35a5e13c'
down_revision = '657c8563c894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS testing_1")
    op.execute("DROP TABLE IF EXISTS names")
    # ### end Alembic commands ###
