"""test

Revision ID: 9539a8ef25fc
Revises: e270117010c1
Create Date: 2025-06-17 17:17:07.067148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9539a8ef25fc'
down_revision = 'e270117010c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
