"""commit

Revision ID: be259015479d
Revises: 60ab35a5e13c
Create Date: 2025-06-17 14:17:49.339804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be259015479d'
down_revision = '60ab35a5e13c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS names")
    # ### end Alembic commands ###
