"""empty message

Revision ID: e0d016c860b4
Revises: 9539a8ef25fc
Create Date: 2025-06-17 17:50:23.208084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d016c860b4'
down_revision = '9539a8ef25fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('names')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('names')
    # ### end Alembic commands ###
