"""replace plaintext email with email_hash and email_encrypted

Revision ID: e270117010c1
Revises: be259015479d
Create Date: 2025-06-17 17:12:23.788355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e270117010c1'
down_revision = 'be259015479d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_hash', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('email_encrypted', sa.LargeBinary(), nullable=False))
        batch_op.drop_index(batch_op.f('email'))
        batch_op.create_unique_constraint(None, ['email_hash'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)
        batch_op.drop_column('email_encrypted')
        batch_op.drop_column('email_hash')

    # ### end Alembic commands ###
