"""Describe your change

Revision ID: 64133f05ef44
Revises: 665a386827c8
Create Date: 2025-07-16 14:05:57.282991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64133f05ef44'
down_revision = '665a386827c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', app.utils.encryption.EncryptedString(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
